keys:
  - &host_loki age1jhd3qnsguqq32zu3zmxk8rlt5j3rgmv4hwqpgjyjrjz6d8rlgeus0r5xs0
  - &host_idun age145cxlqfe52jm7tvgq22k6ft2fqunc5rvmhvmax4pueqz6yhsy3xqdqzkm8

creation_rules:
  - path_regex: hosts/x86/loki/secrets\.yaml$
    key_groups:
      - age:
          - *host_loki

  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *host_loki
          - *host_idun
