# sops-nix wiring for Darwin hosts. Unlike modules/nixos/core/sops.nix,
# there's no per-host secrets.yaml yet - nothing idun needs is host-specific,
# so every secret below points `sopsFile` straight at the Common secrets
# file instead of going through a defaultSopsFile. Add a
# hosts/darwin/<hostname>/secrets.yaml + sops.defaultSopsFile the first time
# a Darwin host needs something host-specific.
#
# idun's age identity is derived from its own SSH host key, same as every
# NixOS host - this requires Remote Login to have been enabled at least once
# so macOS generates /etc/ssh/ssh_host_ed25519_key in the first place (it
# isn't generated by default, unlike NixOS's systemd-managed host key).
# sops-nix's own upstream guidance for Darwin is otherwise a
# separately-generated, separately-backed-up `sops.age.keyFile` (e.g.
# ~/Library/Application Support/sops/age/keys.txt) - switch to that here if
# Remote Login isn't viable on idun. See #12 and docs/adr/0006.
{
  config,
  host,
  lib,
  ...
}:
let
  commonSecretsFile = lib.custom.relativeToRoot "secrets/common.yaml";
in
{
  sops.age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];

  sops.secrets.gitSshPrivateKey = {
    sopsFile = commonSecretsFile;
    owner = host.user.osName;
  };
  sops.secrets.gitFullName = {
    sopsFile = commonSecretsFile;
    owner = host.user.osName;
  };
  sops.secrets.gitEmail = {
    sopsFile = commonSecretsFile;
    owner = host.user.osName;
  };

  # git.nix includes this rendered file for [user] instead of baking
  # name/email into the Nix store via programs.git.settings.
  sops.templates.gitIdentity = {
    owner = host.user.osName;
    content = ''
      [user]
        name = ${config.sops.placeholder.gitFullName}
        email = ${config.sops.placeholder.gitEmail}
    '';
  };
}
