{
  lib,
  config,
  pkgs,
  inputs,
  ...
}:
let
  cfg = config.theme;

  # Base16 template for matugen to generate Material You color schemes
  base16Template = pkgs.writeText "matugen-base16-template.yaml" ''
    system: base16
    slug: matugen-material
    name: Matugen Material
    author: Generated by Matugen
    variant: ${cfg.polarity}
    palette:
      base00: "{{colors.background.default.hex}}"
      base01: "{{colors.surface_container_lowest.default.hex}}"
      base02: "{{colors.surface_container_low.default.hex}}"
      base03: "{{colors.outline_variant.default.hex}}"
      base04: "{{colors.on_surface_variant.default.hex}}"
      base05: "{{colors.on_surface.default.hex}}"
      base06: "{{colors.inverse_on_surface.default.hex}}"
      base07: "{{colors.surface_bright.default.hex}}"
      base08: "{{colors.error.default.hex}}"
      base09: "{{colors.tertiary.default.hex}}"
      base0A: "{{colors.secondary.default.hex}}"
      base0B: "{{colors.primary.default.hex}}"
      base0C: "{{colors.tertiary_container.default.hex}}"
      base0D: "{{colors.primary_container.default.hex}}"
      base0E: "{{colors.secondary_container.default.hex}}"
      base0F: "{{colors.error_container.default.hex}}"
  '';

  # Build all matugen templates including base16 if generate is enabled
  allMatugenTemplates =
    cfg.matugen.templates
    // lib.optionalAttrs cfg.base16.generate {
      __base16 = {
        template = base16Template;
        path = ".local/share/base16/matugen-scheme.yaml";
      };
    };

  # Check if we need to run matugen at all
  needsMatugen =
    cfg.enable && ((lib.length (lib.attrNames cfg.matugen.templates) > 0) || cfg.base16.generate);

  # Generate outputs for all matugen templates
  # Build TOML config for all templates
  templateConfig = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (name: tmpl: ''
      [templates.${name}]
      input_path = "${tmpl.template}"
      output_path = "$out/${tmpl.path}"
    '') allMatugenTemplates
  );

  matugenGenerated =
    pkgs.runCommand "matugen-generated"
      {
        nativeBuildInputs = [ inputs.matugen.packages.${pkgs.stdenv.hostPlatform.system}.default ];
      }
      ''
        mkdir -p $out

        # Create matugen config
        cat > config.toml << EOF
        [config]

        ${templateConfig}
        EOF

        # Generate all templates
        matugen image ${cfg.image} \
          --type ${cfg.matugen.scheme} \
          --mode ${cfg.polarity} \
          --config config.toml
      '';
in
{
  options.theme = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Enable theme configuration";
    };

    image = lib.mkOption {
      type = lib.types.path;
      description = "Path to the wallpaper image";
      example = lib.literalExpression "./wallpapers/waves.jpg";
    };

    icon = {
      package = lib.mkOption {
        type = lib.types.package;
        default = pkgs.papirus-icon-theme;
        description = "The icon theme package to use";
        example = lib.literalExpression "pkgs.qogir-icon-theme";
      };

      name = lib.mkOption {
        type = lib.types.str;
        default = "Papirus";
        description = "The name of the icon theme";
        example = "Qogir";
      };
    };

    pointer = {
      package = lib.mkOption {
        type = lib.types.package;
        default = pkgs.bibata-cursors;
        description = "The cursor theme package to use";
        example = lib.literalExpression "pkgs.capitaine-cursors";
      };

      name = lib.mkOption {
        type = lib.types.str;
        default = "Bibata-Modern-Classic";
        description = "The name of the cursor theme";
        example = "capitaine-cursors";
      };

      size = lib.mkOption {
        type = lib.types.int;
        default = 16;
        description = "The size of the cursor";
      };
    };

    polarity = lib.mkOption {
      type = lib.types.enum [
        "light"
        "dark"
      ];
      default = "dark";
      description = "Whether to use light or dark theme variant";
    };

    base16 = {
      file = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default = null;
        description = "Path to a pre-made base16 YAML color scheme file";
        example = lib.literalExpression "./colors.yaml";
      };

      package = lib.mkOption {
        type = lib.types.nullOr lib.types.package;
        default = null;
        description = ''
          A base16 scheme package (for stylix).
          Common option: pkgs.base16-schemes
        '';
        example = lib.literalExpression "pkgs.base16-schemes";
      };

      generate = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = ''
          Generate base16 scheme from wallpaper using matugen.
          When true, automatically adds a base16 template to matugen configuration.
        '';
      };

      generatedScheme = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default = null;
        internal = true;
        description = "Internal option: path to the generated base16 scheme (set automatically)";
      };
    };

    matugen = {
      scheme = lib.mkOption {
        type = lib.types.nullOr (
          lib.types.enum [
            "scheme-content"
            "scheme-expressive"
            "scheme-fidelity"
            "scheme-fruit-salad"
            "scheme-monochrome"
            "scheme-neutral"
            "scheme-rainbow"
            "scheme-tonal-spot"
            "scheme-vibrant"
          ]
        );
        default = "scheme-expressive";
        description = "Material You scheme type for color generation";
        example = "scheme-tonal-spot";
      };

      templates = lib.mkOption {
        type = lib.types.attrsOf (
          lib.types.submodule {
            options = {
              template = lib.mkOption {
                type = lib.types.path;
                description = "Path to the matugen template file";
                example = lib.literalExpression "./templates/style.css";
              };

              path = lib.mkOption {
                type = lib.types.str;
                description = ''
                  Output path for the generated file (relative to HOME).
                '';
                example = ".config/myapp/colors.css";
              };
            };
          }
        );
        default = { };
        description = ''
          Matugen template configurations.
          Each template will be processed with colors from the wallpaper.
        '';
        example = lib.literalExpression ''
          {
            waybar = {
              template = ./templates/waybar.css;
              path = ".config/waybar/colors.css";
            };
          }
        '';
      };
    };
  };

  config = lib.mkIf cfg.enable {
    assertions =
      let
        base16Options = [
          (cfg.base16.file != null)
          (cfg.base16.package != null)
          cfg.base16.generate
        ];
        base16OptionsSet = lib.count lib.id base16Options;
      in
      [
        {
          assertion = cfg.image != null;
          message = "theme.image must be set when theme is enabled";
        }
        {
          assertion = base16OptionsSet <= 1;
          message = ''
            base16.file, base16.package, and base16.generate are mutually exclusive.
            Only one can be set at a time.
            Currently set: ${
              lib.concatStringsSep ", " (
                lib.filter (x: x != null) [
                  (if cfg.base16.file != null then "file" else null)
                  (if cfg.base16.package != null then "package" else null)
                  (if cfg.base16.generate then "generate" else null)
                ]
              )
            }
          '';
        }
      ];

    # Install generated matugen files to home directory
    home.file = lib.mkIf needsMatugen (
      lib.mapAttrs' (name: tmpl: {
        name = tmpl.path;
        value = {
          source = "${matugenGenerated}/${tmpl.path}";
        };
      }) allMatugenTemplates
    );

    # Expose generated base16 scheme path for other modules (like stylix)
    theme.base16.generatedScheme = lib.mkIf cfg.base16.generate "${matugenGenerated}/.local/share/base16/matugen-scheme.yaml";
  };
}
